# Generated by Django 3.1 on 2020-08-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('uid', models.CharField(max_length=28, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=45)),
            ],
        ),
    ]
