# Generated by Django 3.1 on 2020-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=28)),
                ('access_token', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=45)),
            ],
        ),
    ]
